{% set name = "citeproc-py" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/citeproc_py-{{ version }}.tar.gz
  sha256: f2f9a64cd980706a0cac5deb7579e6f8acc87ce0140520cc9f30262d20c35307

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - lxml                                   # [build_platform != target_platform]
  host:
    - lxml
    - pip
    - python
    - rnc2rng >=2.6.1,!=2.6.2
    - setuptools
    - versioneer
  run:
    - lxml
    - python

test:
  source_files:
    - tests
  imports:
    - citeproc
  commands:
    - pip check
    # nose is not compatible with Python 3.12
    - nosetests --where=tests --ignore-files=citeproc-test.py  # [py<312]
    # I think this is cleaner than patching the missing file in
    # use the tag to keep the tests in sync with the release we are testing
    - curl https://raw.githubusercontent.com/citeproc-py/citeproc-py/v{{ version }}/tests/failing_tests.txt -o tests/failing_tests.txt
    - ls -l
    - ls -l tests
    - python tests/citeproc-test.py --no-update
  requires:
    - git
    - citeproc-py-styles
    - nose
    - pip
    - curl

about:
  home: https://github.com/brechtm/citeproc-py
  summary: Citations and bibliography formatter
  license: BSD-2-Clause AND CC-BY-SA-3.0 AND MIT

  license_file:
    - LICENSE
    - LICENSE_citation-style-language_locales.md
    - LICENSE_citation-style-language_schema.txt

extra:
  recipe-maintainers:
    - mikemhenry
